### ISSUE TITLE
AngularJS directive

### ISSUE THREAD

**Issue by grabbou** [tapmodo/Jcrop#164]
Hi!
Thanks for the amazing work you've done on that project. I've just created AngularJS directive for my needs. If you can link it somewhere in the Readme.md - that'd be cool. Maybe somebody will find it helpful :)

https://github.com/grabbou/angular-crop

**Comment by tapmodo** [comment]
Thanks for that. I don't know much about angular, but your link doesn't appear to be working any longer. I'm going to close the issue, but I'd be happy to add this to the website documentation if you would like to resubmit it or email it to me.

**Comment by grabbou** [comment]
Yeah, I've moved to React a couple of months ago and that library has been discounted. Thanks for your time!
