### ISSUE TITLE
hide drag handles when resizing

### ISSUE THREAD

**Issue by tablatronix** [tapmodo/Jcrop#170]
When you start drawing the first rect, there are no drag handles, after you let go they appear.
It would be nice to hide them when you are mousedown dragging one as well

**Comment by tapmodo** [comment]
This works differently on the newer v2.x branch. I'm going to close this since it's more of a personal taste thing than an issue with Jcrop _per se_. These type of refinements may be incorporated over time, but it's unlikely any such choices will appease every person.

**Comment by tablatronix** [comment]
I think the issue i wa having was that the handles were obscuring the inside crop area slightly
