### ISSUE TITLE
When boxWidth and boxHeight do not give the desired effect

### ISSUE THREAD

**Issue by belgianwolfie** [tapmodo/Jcrop#172]
This is not an issue, more a sharing of knowledge for when someone runs into the same issue as I did.

Somewhere in my global stylesheet I had this: 

img {
	    -webkit-transition: all .1s ease-in-out;
	    -moz-transition: all .1s ease-inout;
	    -o-transition: all .1s ease-in-out;
	    transition: all .1s ease-in-out;
}

this totally wrecked the boxWidth and boxHeight functionality of my Jcrop instance.

**Comment by tapmodo** [comment]
Thanks for the note. I'm going to close this issue since it's related to external CSS, but not specifically related to anything I can fix with Jcrop.
