### ISSUE TITLE
Links broken on JCrop.org and the thumbnail preview demo is broken.

### ISSUE THREAD

**Issue by chrisloughnane** [tapmodo/Jcrop#175]
Hi,

I found these links are broken.

http://jcrop.org/contact
http://jcrop.org/doc/api-basics
http://jcrop.org/doc/api-reference

The thumbnail preview demo is also broken. I tried to compare the live working demo with the download demo and the one difference I found did not correct the problem.

Could you please upload a working demo as I am not happy with the thumbnail preview I have implemented and yours looks much better.

Thanks for a great library.
Chris

**Comment by tapmodo** [comment]
I'm still in the process of updating jcrop.org but some of this has been fixed...specifically the thumbnail code, demo, and documentation has been updated. Thanks for writing! I'm going to close this issue since the site is a known issue and is in progress.
