### ISSUE TITLE
StalePageException by using wicket 6.19

### ISSUE THREAD

**Issue by tschiffler** [tapmodo/Jcrop#179]
Hey, 

I just tried to use the plugin. it works fine with Wicket 6.14, but if I upgrade to wicket 6.19 I get the `org.apache.wicket.core.request.mapper.StalePageException` after opening the Crop-Area

Does anybody have a solution for this problem?

Greetings Thomas

**Comment by tapmodo** [comment]
I'm not familiar with Wicket. This sounds like an issue that is not specifically Jcrop-related. I'm going to close it since there has been no responses and I don't have any course of action to take.
