### ISSUE TITLE
When attempting to crop image the is the scrollbar is reseted 

### ISSUE THREAD

**Issue by santhosh22** [tapmodo/Jcrop#184]
1.Image are displayed with overflow(CSS) in Asp control. Now scrollbar is displayed well.
2. I am able to crop the image without scrollbar movement
3. Move the scrollbar (Image also moving) working perfect
4. when I am trying to do cropping, in the new scrollbar position, then scrollbar getting  is rest to initial position

How to solve this issue?

**Comment by tapmodo** [comment]
This should be fixed in branch WIP-2.x and v2 branches.
I'm closing this issue since it's a little old.
If this is still an issue in v2, please re-open.
