### ISSUE TITLE
Set new tag or move tag 0.9.12 

### ISSUE THREAD

**Issue by Olgagr** [tapmodo/Jcrop#195]
Please, setup new tag or move the last tag. Right now, when you do bower install jcrop the version installed still doesn't contain bower.json.

**Comment by tapmodo** [comment]
Thanks for this note! When I originally set up bower compatibility I didn't fully understand its workings. I've pushed a new 0.9.13 version tag now, for the purposes of bower. I would encourage everyone to try to upgrade to 2.x (which bower should default to now)...
