### ISSUE TITLE
Radio button add on the left of my image

### ISSUE THREAD

**Issue by nicolasbadia** [tapmodo/Jcrop#20]
When I use Jrop, a radio button is add on the left of my image
I've dig a little and find out that it's because of KeyManager. In fact, it create a radio input which seem useful for moving the crop selection with the keyboard.

To hide it, I've change this:

```var $keymgr = $('<input type="radio" />').css({
        position: 'fixed',
        left: '-12000px',
        width: '12px'
      }),

``````

by this :
```var $keymgr = $('<input type="radio" />').css({
        position: 'fixed',
        left: '-12000px',
        width: '12px'
      }),
``````

Since I don't really understand why this input is here, I don't know if this fix is a good one.

Hope somebody will enlighten me about it and fix this properly.

**Comment by abevoelker** [comment]
This CSS hides the radio button for me, as others have suggested:

```css
.jcrop-keymgr {
  opacity: 0;
}
```

**Comment by kevinisaac** [comment]
Is there any disadvantage of just giving it a `display: none;`?

**Comment by naveebantrothu** [comment]
after my image rotation Jcrop Mouse pointer in different place cropping different place image
