### ISSUE TITLE
Boxwidth example code

### ISSUE THREAD

**Issue by mahirbaltaci** [tapmodo/Jcrop#201]
Could you advise me a source code about boxwidth usage (demo page - boxwidth.html does not work with different size images. When I change bigger image return decimal coordinates)

I need these:
Boxwidth, aspect ratio, minsize > target coordinates (int)

My target is: I must reach dimensions correctly (According aspect ratio - 400 x 332 or 544 x 212 etc.)

Is there anyone who can help me?

**Comment by tapmodo** [comment]
Please make sure you're testing against the WIP-2.x branch.
The options should be specified as { boxWidth: 520, bowHeight: 400 }
That is, they should be integers, and should be _camel-cased_

**Comment by tapmodo** [comment]
Closing this issue due to no recent response.
