### ISSUE TITLE
v2 missing trueSize option

### ISSUE THREAD

**Issue by AlfonsoML** [tapmodo/Jcrop#205]
I've tried to update to the new 2.0.1 release, but as far as I can tell, the trueSize option to work with scaled images (http://deepliquid.com/content/Jcrop_Sizing_Issues.html) now it's missing.

Are there any other alternatives now?

BTW, is there any kind of upgrade guide available instead of trial&error or rewrite everything?

**Comment by tapmodo** [comment]
Other than the file names being different, it's intended to be (more or less) a drop-in replacement. I'll investigate the trueSize option...I thought it was there.

**Comment by MauricioArroyo** [comment]
@tapmodo and @AlfonsoML is this trueSize option still available? I see tapmodo closed the issue but I don't see that option in the source code. Thanks!
