### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by crystalcool** [tapmodo/Jcrop#209]
hi, I'm a developer from china, thank you for building this so useful plugin. 
I used it in my code and modify some css in order to adapt to mobile browser.

here is my modification:
jquery.Jcrop.css
------------------------
.jcrop-handle {
  background-color: #333333;
  border: 1px #eeeeee solid;
  width: 19px;
  height: 19px;
  font-size: 1px;
}

.jcrop-handle.ord-n {
  left: 50%;
  margin-left: -10px;
  margin-top: -10px;
  top: 0;
}
.jcrop-handle.ord-s {
  bottom: 0;
  left: 50%;
  margin-bottom: -10px;
  margin-left: -10px;
}
.jcrop-handle.ord-e {
  margin-right: -10px;
  margin-top: -10px;
  right: 0;
  top: 50%;
}
.jcrop-handle.ord-w {
  left: 0;
  margin-left: -10px;
  margin-top: -10px;
  top: 50%;
}
.jcrop-handle.ord-nw {
  left: 0;
  margin-left: -10px;
  margin-top: -10px;
  top: 0;
}
.jcrop-handle.ord-ne {
  margin-right: -10px;
  margin-top: -10px;
  right: 0;
  top: 0;
}
.jcrop-handle.ord-se {
  bottom: 0;
  margin-bottom: -10px;
  margin-right: -10px;
  right: 0;
}
.jcrop-handle.ord-sw {
  bottom: 0;
  left: 0;
  margin-bottom: -10px;
  margin-left: -10px;
}
/* Dragbars */
.jcrop-dragbar.ord-n,
.jcrop-dragbar.ord-s {
  height: 19px;
  width: 100%;
}
.jcrop-dragbar.ord-e,
.jcrop-dragbar.ord-w {
  height: 100%;
  width: 19px;
}
.jcrop-dragbar.ord-n {
  margin-top: -10px;
}
.jcrop-dragbar.ord-s {
  bottom: 0;
  margin-bottom: -10px;
}
.jcrop-dragbar.ord-e {
  margin-right: -10px;
  right: 0;
}
.jcrop-dragbar.ord-w {
  margin-left: -10px;
}

**Comment by tapmodo** [comment]
Great! I'm glad Jcrop worked for you. I would like to review or incorporate your modifications, but they are not in a format I can work with. Please submit a proper pull request, or email me a link to a branch on github.
