### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JustMikey** [tapmodo/Jcrop#220]
The question is rather obvious.

**Comment by IanYates** [comment]
I don't follow this closely but happened to come across your message.  The master branch hasn't had activity in a while but there's a 2.x branch that's got some recent commits.

**Comment by tapmodo** [comment]
Simple answer is absolutely not. I do appologize for the lack of coherent websites/documentation and the branches being in disarray, but even after many years, Jcrop is still in development. WIP-2.x branch is the most current.
