### ISSUE TITLE
Still active project?

### ISSUE THREAD

**Issue by kamov** [tapmodo/Jcrop#240]
Does this is still active project?
I don't see update in last 2 years..

**Comment by tapmodo** [comment]
I can say it most definitely is. Check the WIP-2.x branch for the latest. It doesn't get as much attention as I would like, but expect leaps and bounds when updates do happen.

**Comment by ZaneCEO** [comment]
Thanks for the confirmation :+1:

**Comment by kamov** [comment]
Thanks!
