### ISSUE TITLE
Add coordinates getter convenience method (v2 WIP)

### ISSUE THREAD

**Issue by alexsasharegan** [tapmodo/Jcrop#256]
I've been working on building a ratio toolbar to my Jcrop component. When switching ratios and updating the options, it would be nice to have a `Jcrop.prototype.getCoordinates` method that I can use to initial coordinates on certain actions that update the selection.

The use-case I've been exploring involves 
1. adjusting the crop (typical crop move events), 
2. selecting a new ratio (which updates the selection), 
3. then accepting the crop. 

The `'cropstart', 'cropmove', 'cropend'` events are the only ones that receive the coordinates, but while the coordinates change, none of those events fire in this use case. I still need to get the updated coordinates.

I've made this addition to my source build, but I'm not sure how well it plays into the design:
```js
// inside the Jcrop.prototype extend call:
getCoordinates: function () {
    return this.unscale( this.ui.selection.get() );
},
```

**Comment by alexsasharegan** [comment]
The simple addition is suggested at [pull request #257](https://github.com/tapmodo/Jcrop/pull/257)

**Comment by elhendricks** [comment]
Not sure if this is exactly what you're looking for, but there is a tellSelected method which will get you the coordinates.  If you need them scaled there is also tellScaled method.

**Comment by alexsasharegan** [comment]
I probably should have added somewhere that I was using the WIP-v2 version. I don't believe that method exists in that branch.
