### ISSUE TITLE
Support for Edge browser

### ISSUE THREAD

**Issue by yoshicode** [tapmodo/Jcrop#270]
Hi, I'm very exciting with this plugin, this is awesome.
Here is my wish compatibility with Edge browser.

Thanks in advance.

**Comment by atkulp** [comment]
I'm not one of the devs, but I noticed this issue.  Perhaps there were problems back in July of last year, but everything appears to work in Edge as of March, 2018.  They've made a lot of progress with implementing more specs in Edge, so as long as plugins are standards-compliant, Edge shouldn't have a problem (at least eventually!).
