### ISSUE TITLE
When attempting to crop image that is below the fold, jcrop jumps down the page.

### ISSUE THREAD

**Issue by jrosebr1** [tapmodo/Jcrop#36]
The issue can be seen here: http://www.chicengine.com/pinterest/

To recreate the error:
1. Scroll halfway down the page.
2. Click on an image.
3. Try to drag crop area.
4. You will see that you are "jumped" further down the page.

**Comment by iampuma** [comment]
@BalusC this helped my thanks!

**Comment by cjsinnbeck** [comment]
@tapmodo - I had the same issue in Chrome + Safari, and `keySupport: false` worked for me.

**Comment by evgeniy-maslovskiy** [comment]
Confirm, trick from @BalusC solves the issue, thanks.
