### ISSUE TITLE
Are multiple selection on the same image possible?

### ISSUE THREAD

**Issue by ph0b0s** [tapmodo/Jcrop#55]
**Goal:**
- make multiple selections on the same image
- 2nd selection doesn't cancel 1st selection (both are visible at the same time)

**Additional:**
- concatenate multiple selections in on square polygon

**_Or is it better to make multiple instances of jCrop?_** 
_(but how are they then stacked, they are supposed to be on the same level, not one on top of the other)_

**Comment by lxduan** [comment]
Hi @simonhoefle, may I know if you could share the code of your example? Thank you!

**Comment by simonhoefle** [comment]
Hey @lxduan , of course i do ;-)

I assume that ```imageHandle ``` is a jQuery handle of the image you want to crop...

        /*############################################
         *## Here we create two transparent <canvas> dummy with the same width and height like the
         *## original one which holds the image. This makes it possible to set more than one cropping-     selection
         *############################################*/
            var imgDummyCube = $("<canvas style='position: absolute;top: 0'></canvas>");
            imgDummyCube.attr('width', imageHandle.attr('width'))
                .attr('height', imageHandle.attr('height'))
                .width(imageHandle.width())
                .height(imageHandle.height());
            imageHandle.after(imgDummyCube);

            var imgDummyPanoramic = $("<canvas style='position: absolute;top: 0'></canvas>");
            imgDummyPanoramic.attr('width', imageHandle.attr('width'))
                .attr('height', imageHandle.attr('height'))
                .width(imageHandle.width())
                .height(imageHandle.height());
            imageHandle.after(imgDummyPanoramic);



        /*############################################
         *##
         *## Activating the Jcrop functionality (for the cubeselection) and directly setting the description text for each cropping-area with chaining
         *##
         *############################################*/
            imgDummyCube.Jcrop({
                    aspectRatio: Config.IMAGES.SIZES.CUBE_WIDTH / Config.IMAGES.SIZES.CUBE_WIDTH,
                    minSize: [50, 50],
                    setSelect: cubePreSelection,
                    onSelect: calcCropCube
                }
            )

        /*############################################
         *##
         *## Activating the Jcrop functionality (for the panoramicselection) and directly setting the description text for each cropping-area with chaining
         *##
         *############################################*/
            imgDummyPanoramic.Jcrop({
                    aspectRatio: Config.IMAGES.SIZES.PANORAMIC_WIDTH / Config.IMAGES.SIZES.PANORAMIC_HEIGHT,
                    minSize: [133, 50],
                    setSelect: panPreSelection,
                    onSelect: calcCropPanoramic
                }
            )


The setSelect and onSelect parameters are optional... The important step is creating the two dummy-canvas and the css of the ```.jcrop-holder``` i posted above

**Comment by lxduan** [comment]
Hi @simonhoefle, thank you for the reply. Actually, I'm quite new to Javascript. May I know if it's okay to provide some runnable code, which will be extremely helpful? In my case, I'd like to build something to add multiple bounding boxes for different objects shown in one photo. Sorry to bother you this much..
