### ISSUE TITLE
Jcrop doesn't work with local file URLs

### ISSUE THREAD

**Issue by bhardwick** [tapmodo/Jcrop#58]
We are trying to use local file URLs when running our application locally to simulate images on Amazon S3, but Jcrop breaks when trying to initialize with a local image file.

Example URL:
file:/C:/tomcat/temp/d4d6566c-a6c6-434a-bac4-29fafd3751c7.jpg

If I copy the URL into my browser address bar, I can see the image.

This occurs Firefox and Chrome.

**Comment by abubelinha** [comment]
@bhardwick did you ever solve this?
I'd like to use Jcrop to select areas of a local image files without installing a webserver. Is this not possible?  

Thanks
@abubelinha
